import type { Locale } from "./types";

export const customerAuthCopy = {
  vi: {
    eyebrow: "Tài khoản khách hàng", login: "Đăng nhập", register: "Tạo tài khoản", forgotPassword: "Quên mật khẩu", resetPassword: "Đặt lại mật khẩu", verifyEmail: "Xác minh email", email: "Email", password: "Mật khẩu", fullName: "Họ và tên", submitLogin: "Đăng nhập", submitRegister: "Tạo tài khoản", submitForgot: "Gửi liên kết đặt lại", submitReset: "Đặt lại mật khẩu", submitVerify: "Xác minh email", backHome: "Về trang chủ", noAccount: "Chưa có tài khoản?", hasAccount: "Đã có tài khoản?", forgotPrompt: "Quên mật khẩu?", genericAccepted: "Nếu thông tin hợp lệ, chúng tôi đã tiếp nhận yêu cầu của bạn.", resetDescription: "Nhập mật khẩu mới rồi xác nhận để sử dụng liên kết này.", verifyDescription: "Xác nhận để hoàn tất việc xác minh email của bạn.", tokenMissing: "Liên kết này không hợp lệ hoặc đã thiếu thông tin xác minh.", unavailable: "Tính năng tài khoản hiện chưa khả dụng.", requestFailed: "Không thể hoàn tất yêu cầu lúc này. Vui lòng thử lại.", passwordRule: "Mật khẩu cần ít nhất 12 ký tự và tối đa 72 byte UTF-8.", passwordInvalid: "Mật khẩu cần ít nhất 12 ký tự và tối đa 72 byte UTF-8.", signedIn: "Tài khoản của bạn", verified: "Email đã xác minh", unverified: "Email chưa xác minh", expires: "Phiên đăng nhập hết hạn", resend: "Gửi lại email xác minh", signOut: "Đăng xuất", signOutAll: "Đăng xuất khỏi mọi thiết bị", signedOut: "Bạn đã đăng xuất.", oauthError: "Không thể hoàn tất đăng nhập bằng dịch vụ bên thứ ba. Vui lòng thử lại.", or: "hoặc", google: "Tiếp tục với Google", facebook: "Tiếp tục với Facebook", loading: "Đang tải..."
  },
  en: {
    eyebrow: "Customer account", login: "Sign in", register: "Create account", forgotPassword: "Forgot password", resetPassword: "Reset password", verifyEmail: "Verify email", email: "Email", password: "Password", fullName: "Full name", submitLogin: "Sign in", submitRegister: "Create account", submitForgot: "Send reset link", submitReset: "Reset password", submitVerify: "Verify email", backHome: "Back to home", noAccount: "New here?", hasAccount: "Already have an account?", forgotPrompt: "Forgot your password?", genericAccepted: "If the details are valid, we have accepted your request.", resetDescription: "Enter a new password, then confirm before using this link.", verifyDescription: "Confirm to complete your email verification.", tokenMissing: "This link is invalid or is missing verification information.", unavailable: "Customer accounts are not available at the moment.", requestFailed: "We could not complete your request. Please try again.", passwordRule: "Password must have at least 12 characters and at most 72 UTF-8 bytes.", passwordInvalid: "Password must have at least 12 characters and at most 72 UTF-8 bytes.", signedIn: "Your account", verified: "Email verified", unverified: "Email not verified", expires: "Session expires", resend: "Resend verification email", signOut: "Sign out", signOutAll: "Sign out everywhere", signedOut: "You have signed out.", oauthError: "We could not complete the third-party sign-in. Please try again.", or: "or", google: "Continue with Google", facebook: "Continue with Facebook", loading: "Loading..."
  }
} as const;

export type CustomerAuthCopy = { [Key in keyof typeof customerAuthCopy.vi]: string };
export function copyFor(locale: Locale): CustomerAuthCopy { return customerAuthCopy[locale]; }
