import Link from "next/link";
import { Bell, Clock3 } from "lucide-react";
import type { CartLocale } from "../types";

const slots = ["10:30–12:00", "12:00–13:30", "17:00–18:30", "18:30–20:00"];

export function PrelaunchCart({ locale }: { locale: CartLocale }) {
  const vi = locale === "vi";
  const copy = vi ? { eyebrow: "Bếp Nhà Mình · TP.HCM", title: "Bếp chưa mở nhận đơn", body: "Bếp đang hoàn thiện những khâu cuối cùng. Bạn có thể để lại thông tin để nhận ngày mở bán và catalog hiện tại.", notify: "Nhận thông báo mở bán", menu: "Xem thực đơn dự kiến", slots: "Khung giờ giao dự kiến tại TP.HCM", note: "Các khung giờ sẽ được xác nhận khi bếp bắt đầu nhận đơn." } : { eyebrow: "Bếp Nhà Mình · Ho Chi Minh City", title: "Orders are not open yet", body: "The kitchen is finishing the final preparations. Leave your details to receive the opening date and current catalog.", notify: "Get opening updates", menu: "View the planned menu", slots: "Planned delivery times in Ho Chi Minh City", note: "Delivery times will be confirmed when the kitchen opens orders." };
  return <main className="botanical-section botanical-soft min-h-[calc(100vh-10rem)] py-14 md:py-20"><div className="mx-auto max-w-5xl px-5"><section className="grid gap-8 border-y border-olive-700/15 py-10 md:grid-cols-[minmax(0,1fr)_22rem] md:items-center md:py-14"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-wood-500">{copy.eyebrow}</p><h1 className="mt-3 font-serif text-4xl leading-tight text-olive-900 md:text-5xl">{copy.title}</h1><p className="mt-5 max-w-xl text-base leading-7 text-muted">{copy.body}</p><div className="mt-7 flex flex-wrap gap-3"><Link href={`/${locale}#waitlist`} className="inline-flex min-h-11 items-center gap-2 rounded-md bg-olive-700 px-4 text-sm font-semibold text-white"><Bell size={17} aria-hidden="true" />{copy.notify}</Link><Link href={`/${locale}/menu`} className="inline-flex min-h-11 items-center rounded-md border border-olive-700/25 px-4 text-sm font-semibold text-olive-900 hover:bg-white">{copy.menu}</Link></div></div><aside className="border border-olive-700/15 bg-white p-5 shadow-soft"><div className="flex items-center gap-2 text-olive-900"><Clock3 size={19} aria-hidden="true" /><h2 className="font-serif text-2xl">{copy.slots}</h2></div><p className="mt-3 text-sm leading-6 text-muted">{copy.note}</p><ul className="mt-5 grid gap-2">{slots.map((slot) => <li key={slot} className="border-t border-olive-700/10 pt-3 text-sm font-semibold text-olive-900">{slot}</li>)}</ul></aside></section></div></main>;
}
